# Generated by Django 3.1.7 on 2021-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210828_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='created',
        ),
        migrations.AddField(
            model_name='education',
            name='created_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='created_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
