# Generated by Django 3.2.5 on 2022-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20220717_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstyle',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
