# Generated by Django 3.2.5 on 2023-02-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_workstyle_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_languages', models.JSONField(blank=True, default=list, null=True)),
                ('frameworks', models.JSONField(blank=True, default=list, null=True)),
                ('developer_tools', models.JSONField(blank=True, default=list, null=True)),
                ('libraries', models.JSONField(blank=True, default=list, null=True)),
                ('other', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='workstyle',
            name='profile',
        ),
        migrations.AddField(
            model_name='education',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='about_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='description_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='about_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_tab_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_tab_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='education', to='user.Education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(blank=True, related_name='education', to='user.Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro_tab_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro_tab_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='user.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_intro_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_intro_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='workstyle',
            field=models.ManyToManyField(blank=True, related_name='workstyle', to='user.WorkStyle'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workstyle',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workstyle',
            name='about_lt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.techskill'),
        ),
    ]
