# Generated by Django 3.2.5 on 2023-02-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20230203_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='education',
            name='about_lt',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description_lt',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='about_lt',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_lt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_lt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_tab_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_tab_lt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intro_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intro_lt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intro_tab_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intro_tab_lt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_intro_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='short_intro_lt',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description_lt',
        ),
        migrations.RemoveField(
            model_name='workstyle',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='workstyle',
            name='about_lt',
        ),
    ]
