services:
  web:
    build:
      context: ./src
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8002
    env_file:
      - ./src/.env
#  nginx:
#    build:
#      context: ./nginx/
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/html/:/usr/share/nginx/html/
#      - ./nginx/conf.d/:/etc/nginx/conf.d/
#  dns:
#    build:
#      context: ./dns/
#    restart: always
#    ports:
#      - 53:53
#      - 53:53/udp
#    volumes:
#      - ./dns/named.conf:/etc/bind/named.conf
#      - ./dns/zone/:/etc/bind/zone/
#    command: named -c /etc/bind/named.conf -g -u named