version: '3.9'

services:
  app:
    build:
      context: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - ./src:/app
      - logs:/app/logs
    ports:
      - 8002:8002
    environment:
      - DJANGO_DEBUG=0

volumes:
  logs:
