# Generated by Django 3.2.5 on 2021-08-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210828_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
    ]
