# Generated by Django 3.1.7 on 2021-08-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210828_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
