# Generated by Django 3.1.7 on 2021-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210828_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
