# Generated by Django 3.1.7 on 2021-08-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_education_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='created',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
