# Generated by Django 3.2.5 on 2021-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_profile_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro_tab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
