# Generated by Django 3.2.5 on 2021-08-29 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_description_experience_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStyle',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
