# Generated by Django 3.1.7 on 2021-08-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210828_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='created',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
