# Generated by Django 3.2.5 on 2021-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_second',
            field=models.TextField(blank=True, null=True),
        ),
    ]
