# Generated by Django 3.2.5 on 2021-08-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='company',
        ),
    ]
