# Generated by Django 3.2.5 on 2021-08-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_workstyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio_second',
            new_name='bio_tab',
        ),
    ]
